### PR TITLE
Chore: Update nuxt

### LINKED ISSUE #4: Update to Nuxt3 (now that it's available)
Not sure if you're interested in that @wmnnd?

### PR DESCRIPTION
**Pull request by pascalwengerter**
This is heavily _WIP_, however rendering the basic docs already works (translations are the most pressing topic I suppose), as expected with quite some warnings

Closes #4 once it's done 🙌🏽 

Note: `npm run dev` works, static page generation fails because it exceeds the call stack and fails CI. Needs work

### CODE REVIEW

**Comment by pascalwengerter** [comment]
Still planning on eventually pulling through with this btw 😬

**Comment by wmnnd** [comment]
Haha, I was actually thinking about this the other day … or if we should try to make the jump to Astro or Hugo (as you had suggested previously). Any favorite site generators at the moment? :blush:

**Comment by pascalwengerter** [comment]
> Haha, I was actually thinking about this the other day … or if we should try to make the jump to Astro or Hugo (as you had suggested previously). Any favorite site generators at the moment? :blush: 

I'd vote for staying with Nuxt, but I may be a bit biased because that's what I've worked with most from those three (and the project is already set up I it), and from what I've seen the docs wouldn't profit a lot from the improved performance that Hugo would bring...

**Comment by pascalwengerter** [comment]
Taking another look here since the Nuxt ecosystem has evolved/stabilized in the meantime. Looking forward to dragging this across the finish line eventually 😇

**Comment by wmnnd** [comment]
Hey, thanks for looking into this again!  I hope you haven’t put in too much work now - because I’ve actually been working on a complete redesign of the website :scream: 
If you’re curious, you can take a look here: beta [dot] keila [dot] io (I’ve been too lazy to set up basic auth^^)

**Comment by pascalwengerter** [comment]
> Hey, thanks for looking into this again! I hope you haven’t put in too much work now - because I’ve actually been working on a complete redesign of the website 😱 If you’re curious, you can take a look here: beta [dot] keila [dot] io (I’ve been too lazy to set up basic auth^^)

I'm mostly doing this as a personal learning of sorts 😉 so all good. Will the redesign happen on top of the current codebase? Then I'd try to pull through with my PR

**Comment by wmnnd** [comment]
Nope, I gave Astro a try and I'm currently much happier with it than with Nuxt. It does a lot of cool things like optimizing images, and it loads way less JS on the page.

**Comment by pascalwengerter** [comment]
Closing then, looking forward to the redesign/relaunch!

**Pull request closed without merging**
